name: resnext29
stages:
  - n_block: 3
    n_group: 32
    c_mid: 4
    c_out: 256
  - n_block: 3
    n_group: 32
    c_mid: 8
    c_out: 512
  - n_block: 3
    n_group: 32
    c_mid: 16
    c_out: 1024
data:
  data_sec: 1
  valid_sec: 0.1
  batch_size: 128
optimizer:
  type: asam
  params:
    lr: 0.1
    rho: 1
    eta: 0.01
    weight_decay: 0.0005
scheduler:
  type: multistep
  params:
    milestones:
      - 60
      - 120
      - 180
    gamma: 0.1
augmentation:
  - baseline
  - mixup
  - cutout
  - cutmix
max_epoch: 200
